# Generated by Django 2.1.5 on 2019-02-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='slug',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.IntegerField(choices=[(1, 'Accident'), (2, 'Fraud'), (3, 'Robbery'), (4, 'Bullying'), (5, 'Cyber Crime'), (6, 'Other')], default=1),
        ),
    ]
